{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sites-rupy201.fullname" . }}
data:
{{ .Values.env.config | toYaml | indent 2 }}
---
{{- end}}

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sites-rupy201.fullname" . }}
stringData:
{{ .Values.env.secrets | toYaml | indent 2 }}
---
{{- end}}


# TLS SECRET FOR THE INGRESS PIECE
apiVersion: v1
kind: Secret
metadata:
  name: tls-ingress-cert-secrets
  annotations:
    harness.io/skip-versioning: "true"
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
type: kubernetes.io/tls