apiVersion: v1
kind: Service
metadata:
  name: {{ include "sites-rupy201.fullname" . }}
  labels:
    {{- include "sites-rupy201.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}         
  selector:
    {{- include "sites-rupy201.selectorLabels" . | nindent 4 }}
